import 'dart:convert';

//import 'package:coconut_wallet/packages/bc-ur-dart/lib/cbor_lite.dart';
//import 'package:coconut_wallet/packages/bc-ur-dart/lib/ur.dart';
//import 'package:coconut_wallet/packages/bc-ur-dart/lib/ur_encoder.dart';
import 'package:coconut_wallet/utils/logger.dart';
import 'package:coconut_wallet/utils/type_converter_utils.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:cbor/cbor.dart';
import 'package:ur/ur_decoder.dart';
import 'package:ur/cbor_lite.dart';
import 'package:ur/ur.dart';
import 'package:ur/ur_encoder.dart';

void main() {
  group('BC-UR Decoder Tests', () {
    test('[keystone(multicoin) + bluewallet]: should decode crypto-account UR and extract values correctly', () {
      final urParts = [
        'UR:CRYPTO-ACCOUNT/5586-3/LPCFBZTDAXCFADMOCYTONTCWIOHDLNRSLSDYPAFZFEMWGRHPYLEYGWDWDPTILRYKHPFZBTDRDWMKFEFHLOHDQZCXIMAEGUDALFVYSFWSBGADNSDSCMFHDKSAFHCERODSZMCEDLHPPASGQZDMPYPLHDNYDADSENPLSWFPUYREGLWYPMSNCLPLRLBARDDEFDLYCKJNGSKGNTDSRTPLUTTPEYMUONTPAXEYONUEHYDTRSHGLTJEDTGHYLWSFRRDIMCKTSLFTLFWAADYOLURHHEHIYCNJSLTWKKEJTIAECSAYTGOMUAOPD',
        'UR:CRYPTO-ACCOUNT/5587-3/LPCFBZTEAXCFADMOCYTONTCWIOHDLNATAYJECTTAADMUTAADDLOSAOWKAXHDCLAXPSCWJYAYREQDBASBQDCNZEOTDIBWTLWPDWGAFGKESOHLNDQDIAUOHYPMDNGEUYZMAAHDCXTOTSMTSFWNEEZMTEIYLBTPDLWNEOKGCABAIHNYMHNESESWEHWKDAZMGMASSTMDLKAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSDWYKAEYKAEYKAOCYTOGWNTAMAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYMWENSGWMNTURRSEC',
        'UR:CRYPTO-ACCOUNT/5588-3/LPCFBZTYAXCFADMOCYTONTCWIOHDLNOEADCYTOGWNTAMAOLSTAADMWTAADDLOSAOWKAXHDCLAOSKYTWDKECPFRRTETTKZSTSHKZOGSURPRSKRSRFCHFHZMHTGYVDMOJPMHPDHLCNIDAAHDCXFYUEDEYLPDESGLTPRFGRKETACXGRTIGOINVDHNNBSTSFKPNTPYKGKGJLCYDPTTASAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSGHYKAEYKAEYKAOCYTOGWNTAMAXAXATTAADDYOEADLRAEWKLAWKAXAEAYLBQDCMFY',
        'UR:CRYPTO-ACCOUNT/5589-3/LPCFBZTLAXCFADMOCYTONTCWIOHDLNOEADCYTOGWNTAMAOLSTAADMWTAADDLOSAOWKAXHDCLAOSKYTWDKECPFRRTETTKZSTSHKZOGSURPRSKRSRFCHFHZMHTGYVDMOJPMHPDHLCNIDAAHDCXFYUEDEYLPDESGLTPRFGRKETACXGRTIGOINVDHNNBSTSFKPNTPYKGKGJLCYDPTTASAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSGHYKAEYKAEYKAOCYTOGWNTAMAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCEWEEEIY',
        'UR:CRYPTO-ACCOUNT/5590-3/LPCFBZTBAXCFADMOCYTONTCWIOHDLNROLUHPPLNLFYATMOHTTPMDGTTPDMLOONYNYLHPKKCPNLDNGRWKFRKGGELSGTBWLNSOPLPDLEMUUYHHATMDKPVLKNJLBBHFIATAZOFYBSMDIYHHKSURNEGYLUZTHTZECFHEYKFTSWRKDNJYFSGMVTISLNZSNETSCYLOTAYARTKBFYDIWNBNUOTPDYMUOTADAOAOAMURTPEHMUOELTNNDTOYYKYKYKYKYLCSTYLYTDNDAHAEAAUETPEHMOOTLPLRWKJYJYYLAXAYBGVEZCREJS',
        'UR:CRYPTO-ACCOUNT/5591-3/LPCFBZTSAXCFADMOCYTONTCWIOHDLNCYLEFPHNTBTAADMHTAADMWTAADDLOSAOWKAXHDCLAXNDWYPRCKFLHKJSFXKPUOKECKYLGUSWGSINNLRODTIDUOLPECFEPAWNPYJEWPGMRPAAHDCXZMUYMYOTBDWZSTHGLTGAJSRDIDBDFHWEATLDMYVAHTHDCWJLBZJPLSRKBYHYBKCXAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSEHYKAEYKAEYKAOCYTOGWNTAMAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYJSFXWSNT',
        'UR:CRYPTO-ACCOUNT/5592-3/LPCFBZTPAXCFADMOCYTONTCWIOHDLNRSLSDYPAFZFEMWGRHPYLEYGWDWDPTILRYKHPFZBTDRDWMKFEFHLOHDQZCXIMAEGUDALFVYSFWSBGADNSDSCMFHDKSAFHCERODSZMCEDLHPPASGQZDMPYPLHDNYDADSENPLSWFPUYREGLWYPMSNCLPLRLBARDDEFDLYCKJNGSKGNTDSRTPLUTTPEYMUONTPAXEYONUEHYDTRSHGLTJEDTGHYLWSFRRDIMCKTSLFTLFWAADYOLURHHEHIYCNJSLTWKKEJTIAECSAYTFHFNHPKB',
        'UR:CRYPTO-ACCOUNT/5593-3/LPCFBZTAAXCFADMOCYTONTCWIOHDLNONASJSTTMTNSMDUYLFYNOLMTDPAOKTLNADHDCSDWDTRLKOYLCLTKADSKIACTUODLFRKPPRBKOTKGMKDKBSJYVLOYYLKNPMGALGMWWTKIWEREMOMWTTJOCLZOMETSVYHSDTMYDYHSTSFETTFZSGPDCLGYGHVOEODIMWJZWYYLIMSRDWVTPYAATAAXEHOXTPADEYOTATHECFCEHFADJKCSOYYLCYFRGWISAACFSNFDFYATEOOYAMHLADSSCPYKLTAEZTNYHNECSGVLADMHNNDP',
        'UR:CRYPTO-ACCOUNT/5594-3/LPCFBZTNAXCFADMOCYTONTCWIOHDLNOEADCYTOGWNTAMAOLSTAADMWTAADDLOSAOWKAXHDCLAOSKYTWDKECPFRRTETTKZSTSHKZOGSURPRSKRSRFCHFHZMHTGYVDMOJPMHPDHLCNIDAAHDCXFYUEDEYLPDESGLTPRFGRKETACXGRTIGOINVDHNNBSTSFKPNTPYKGKGJLCYDPTTASAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSGHYKAEYKAEYKAOCYTOGWNTAMAXAXATTAADDYOEADLRAEWKLAWKAXAEAYFXBZSEHP',
        'UR:CRYPTO-ACCOUNT/5595-3/LPCFBZUYAXCFADMOCYTONTCWIOHDLNCYLEFPHNTBTAADMHTAADMWTAADDLOSAOWKAXHDCLAXNDWYPRCKFLHKJSFXKPUOKECKYLGUSWGSINNLRODTIDUOLPECFEPAWNPYJEWPGMRPAAHDCXZMUYMYOTBDWZSTHGLTGAJSRDIDBDFHWEATLDMYVAHTHDCWJLBZJPLSRKBYHYBKCXAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSEHYKAEYKAEYKAOCYTOGWNTAMAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYLUHKKESW',
        'UR:CRYPTO-ACCOUNT/5596-3/LPCFBZUOAXCFADMOCYTONTCWIOHDLNROLUHPPLNLFYATMOHTTPMDGTTPDMLOONYNYLHPKKCPNLDNGRWKFRKGGELSGTBWLNSOPLPDLEMUUYHHATMDKPVLKNJLBBHFIATAZOFYBSMDIYHHKSURNEGYLUZTHTZECFHEYKFTSWRKDNJYFSGMVTISLNZSNETSCYLOTAYARTKBFYDIWNBNUOTPDYMUOTADAOAOAMURTPEHMUOELTNNDTOYYKYKYKYKYLCSTYLYTDNDAHAEAAUETPEHMOOTLPLRWKJYJYYLAXAYBGMNGMWPOS',
        'UR:CRYPTO-ACCOUNT/5597-3/LPCFBZUTAXCFADMOCYTONTCWIOHDLNCYLEFPHNTBTAADMHTAADMWTAADDLOSAOWKAXHDCLAXNDWYPRCKFLHKJSFXKPUOKECKYLGUSWGSINNLRODTIDUOLPECFEPAWNPYJEWPGMRPAAHDCXZMUYMYOTBDWZSTHGLTGAJSRDIDBDFHWEATLDMYVAHTHDCWJLBZJPLSRKBYHYBKCXAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSEHYKAEYKAEYKAOCYTOGWNTAMAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYCWWPRPGR',
        'UR:CRYPTO-ACCOUNT/5598-3/LPCFBZUEAXCFADMOCYTONTCWIOHDLNROLUHPPLNLFYATMOHTTPMDGTTPDMLOONYNYLHPKKCPNLDNGRWKFRKGGELSGTBWLNSOPLPDLEMUUYHHATMDKPVLKNJLBBHFIATAZOFYBSMDIYHHKSURNEGYLUZTHTZECFHEYKFTSWRKDNJYFSGMVTISLNZSNETSCYLOTAYARTKBFYDIWNBNUOTPDYMUOTADAOAOAMURTPEHMUOELTNNDTOYYKYKYKYKYLCSTYLYTDNDAHAEAAUETPEHMOOTLPLRWKJYJYYLAXAYBGFDWYPDVL',
        'UR:CRYPTO-ACCOUNT/5599-3/LPCFBZURAXCFADMOCYTONTCWIOHDLNCALFDRLBBSTPMOGATPDMEOUYYKDWZMCNYLPEFXGOBDDMHLRFTLWKKNMYVTGMTKPTWZUYCYLADYNBSSCNNYADAEUYMKJTZODRGHJLQZJPKSTETOWPBAWSJOJOJNLGCTKSKOKNBKOSJZJTONKIMKFDGATSPLKIVEFSCERECMEMBBLTBDBYOSTPADEOOEATTAAXDYONTPLTDEMYWKLNWEEHAEAOWSTORDNECESNGSNYURAOEOONTPLPDYHFLYJOAXWKLOWYMSENSAWNFTEMSBCT',
        'UR:CRYPTO-ACCOUNT/5600-3/LPCFBZVTAXCFADMOCYTONTCWIOHDLNCYLEFPHNTBTAADMHTAADMWTAADDLOSAOWKAXHDCLAXNDWYPRCKFLHKJSFXKPUOKECKYLGUSWGSINNLRODTIDUOLPECFEPAWNPYJEWPGMRPAAHDCXZMUYMYOTBDWZSTHGLTGAJSRDIDBDFHWEATLDMYVAHTHDCWJLBZJPLSRKBYHYBKCXAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSEHYKAEYKAEYKAOCYTOGWNTAMAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYUOCXFGUO',
      ];

      final decodedData = decodeAndVerifyUR(urParts);
      // 필요한 경우 decodedData를 사용하여 추가 검증 수행
    });

    test('[keystone(bct-only) + nunchuk]: should decode crypto-account UR and extract values correctly', () {
      final urParts = [
        'UR:CRYPTO-ACCOUNT/393-3/LPCFADLDAXCFADMOCYHEBDONCMHDLNCYFPLYFETLTAADMHTAADMWTAADDLOSAOWKAXHDCLAXBASOOELNRESRCHCLENLUPMTPTSRYGHSPMTFSSNUEGYBKJNAYKEIDSKDEFXDTWDSOAAHDCXLTISMSMYIALATLIYMSFRTKCMIHWKLOHYPTSKTNJKDECFBTLDNYCSAXSGHTGMFGDYAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSEHYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYJYCTZCFH',
        'UR:CRYPTO-ACCOUNT/394-3/LPCFADLEAXCFADMOCYHEBDONCMHDLNTSMUVTCTUOJNJKGRHPYLEYGWDWDPTILRWKYLDMFYKKYKMSKOVOVDFSIYKERYNLSKLTSOGLJOHDMTVSFDPRAYWLDIESHPYKDICTJOSTPEKPASFLFPAEGWGSNBGAJPOXJEWKFNHTTSWFGOAEDAWTAHTKMYADVYIAPFBYBTLUTDHYKISSFPNLUTTPEYMUONTPAXEYONUEHYDTRSHGLTJEDTGHYLWSSNDAFWYTCLWMIDLGVLDYOLURHHEHIYCNJSLTWKKEJTGMBBJOBEJORPVDRN',
        'UR:CRYPTO-ACCOUNT/395-3/LPCFADLUAXCFADMOCYHEBDONCMHDLNJLTEKGIDTAADMUTAADDLOSAOWKAXHDCLAOAEKPFSHPYAWSSNZMESJKNTCXFTWKBASSMSZOFMSWFWROSNBBRLGMETZMSBMKFYIMAAHDCXWPHHCWESOSBBFPCAFZAXMDWZRPLNSWIAGSDNJZKNCEGYOYMERNPLUTGASKDRJNVLAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSDWYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYONCHKSAOHHRKBYLE',
        'UR:CRYPTO-ACCOUNT/396-3/LPCFADLKAXCFADMOCYHEBDONCMHDLNTSMUVTCTUOJNJKGRHPYLEYGWDWDPTILRWKYLDMFYKKYKMSKOVOVDFSIYKERYNLSKLTSOGLJOHDMTVSFDPRAYWLDIESHPYKDICTJOSTPEKPASFLFPAEGWGSNBGAJPOXJEWKFNHTTSWFGOAEDAWTAHTKMYADVYIAPFBYBTLUTDHYKISSFPNLUTTPEYMUONTPAXEYONUEHYDTRSHGLTJEDTGHYLWSSNDAFWYTCLWMIDLGVLDYOLURHHEHIYCNJSLTWKKEJTGMBBJOBEVTAXDPEO',
        'UR:CRYPTO-ACCOUNT/397-3/LPCFADLGAXCFADMOCYHEBDONCMHDLNSNTDHSHTASQZJPUYLFYNOLMTDPAOKTLNAEWKKOIHKNZOHYTYIEGMZEJSHLLUBGISHECKWFDKMHAETLLPJZHKVLGEEHDIMSVOEMEOWYFERFBTCTHSLTDIUYDLDRWZJSBTIAATMDSEMTOYLOKGHKRTBZZTDTYAJTESLUBZLOCSAADLLFJSNSAATAAXEHOXTPADEYOTATHECFCEHFADJKCSOYYLCYSNTIFZVLCFFRTSJZVTEOOYAMHLADSSCPYKLTAEZTNYGYBBKSBKRFSGVYEH',
        'UR:CRYPTO-ACCOUNT/398-3/LPCFADMNAXCFADMOCYHEBDONCMHDLNCYFPLYFETLTAADMHTAADMWTAADDLOSAOWKAXHDCLAXBASOOELNRESRCHCLENLUPMTPTSRYGHSPMTFSSNUEGYBKJNAYKEIDSKDEFXDTWDSOAAHDCXLTISMSMYIALATLIYMSFRTKCMIHWKLOHYPTSKTNJKDECFBTLDNYCSAXSGHTGMFGDYAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSEHYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYLTWKBZMH',
        'UR:CRYPTO-ACCOUNT/399-3/LPCFADMYAXCFADMOCYHEBDONCMHDLNROFZNDKIAHJZVTMOHTTPMDGTTPDMLOONYNYLHPKKCPBTKSRKCAUEGLZOHHLTJNSBFXHYREGLNNTYGDLPOLRSRKCTSWMHJNIAKPJYNEMYNLGOHHKSOSHPBTRYASJSEHNLFWRDNSQZRSKBJZHEWPGHJTCKRSGWRNYTTYDIVAEHHPOXSKJOFRUOTPDYMUOTADAOAOAMURTPEHMUOELTNNDTOYYKYKYKYKYLCSCPVSIHGHVOAEAAUETPEHMOOTLPLRWKJYJYYLAXAYBGMWJTBTLR',
        'UR:CRYPTO-ACCOUNT/400-3/LPCFADMHAXCFADMOCYHEBDONCMHDLNCYFPLYFETLTAADMHTAADMWTAADDLOSAOWKAXHDCLAXBASOOELNRESRCHCLENLUPMTPTSRYGHSPMTFSSNUEGYBKJNAYKEIDSKDEFXDTWDSOAAHDCXLTISMSMYIALATLIYMSFRTKCMIHWKLOHYPTSKTNJKDECFBTLDNYCSAXSGHTGMFGDYAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSEHYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYETAHZMWD',
        'UR:CRYPTO-ACCOUNT/401-3/LPCFADMEAXCFADMOCYHEBDONCMHDLNKPMOZSDIBNTPMOGATPDMEOUYYKDWZMCNYNAXDPCEHDYNDSJLKKLKPFLEADBNLBOTCEFZFGIMBATYLPAESGVAHDGOYLRLZSLYFWFLJSSGDAHDFXCFCXKETBMOCNLSFZMWCLRYASKPDTURVEDKREMWKGVOMTRLTIRTHEEYJTDTHELUFLADOSTPADEOOEATTAAXDYONTPLTDEMYWKLNWEEHAEAOWSETDARLZOFRTEPRETAOEOONTPLPDYHFLYJOAXWKLOWYOLCHJOCSLETYNDCF',
      ];

      final decodedData = decodeAndVerifyUR(urParts);
      // 필요한 경우 decodedData를 사용하여 추가 검증 수행
      Logger.log('--> result: $decodedData');
    });

    test('[keystone(bct-only) + bluewallet]: should decode crypto-account UR and extract values correctly', () {
      final urParts = [
        'UR:CRYPTO-ACCOUNT/12-3/LPBNAXCFADMOCYHEBDONCMHDLNSNTDHSHTASQZJPUYLFYNOLMTDPAOKTLNAEWKKOIHKNZOHYTYIEGMZEJSHLLUBGISHECKWFDKMHAETLLPJZHKVLGEEHDIMSVOEMEOWYFERFBTCTHSLTDIUYDLDRWZJSBTIAATMDSEMTOYLOKGHKRTBZZTDTYAJTESLUBZLOCSAADLLFJSNSAATAAXEHOXTPADEYOTATHECFCEHFADJKCSOYYLCYSNTIFZVLCFFRTSJZVTEOOYAMHLADSSCPYKLTAEZTNYGYBBKSBKVWCXSNID',
        'UR:CRYPTO-ACCOUNT/13-3/LPBTAXCFADMOCYHEBDONCMHDLNOEADCYETTIREVYAOLSTAADMWTAADDLOSAOWKAXHDCLAXPACFNDJELGWPKIPAVAIYNDLDAYCYHFFWJNFDKSWYPAJPTOWPBSOLHLEMRPIHGDGYAAHDCXEONYEYIMWNVEZMTLLYGUOETNLEVEADFEMEQZJNMSHFQDJOGLFHVWZOADYNLSFZFMAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSGHYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYHGWNPTME',
        'UR:CRYPTO-ACCOUNT/14-3/LPBAAXCFADMOCYHEBDONCMHDLNROFZNDKIAHJZVTMOHTTPMDGTTPDMLOONYNYLHPKKCPBTKSRKCAUEGLZOHHLTJNSBFXHYREGLNNTYGDLPOLRSRKCTSWMHJNIAKPJYNEMYNLGOHHKSOSHPBTRYASJSEHNLFWRDNSQZRSKBJZHEWPGHJTCKRSGWRNYTTYDIVAEHHPOXSKJOFRUOTPDYMUOTADAOAOAMURTPEHMUOELTNNDTOYYKYKYKYKYLCSCPVSIHGHVOAEAAUETPEHMOOTLPLRWKJYJYYLAXAYBGSNLRCLTS',
        'UR:CRYPTO-ACCOUNT/15-3/LPBSAXCFADMOCYHEBDONCMHDLNTSMUVTCTUOJNJKGRHPYLEYGWDWDPTILRWKYLDMFYKKYKMSKOVOVDFSIYKERYNLSKLTSOGLJOHDMTVSFDPRAYWLDIESHPYKDICTJOSTPEKPASFLFPAEGWGSNBGAJPOXJEWKFNHTTSWFGOAEDAWTAHTKMYADVYIAPFBYBTLUTDHYKISSFPNLUTTPEYMUONTPAXEYONUEHYDTRSHGLTJEDTGHYLWSSNDAFWYTCLWMIDLGVLDYOLURHHEHIYCNJSLTWKKEJTGMBBJOBELBGOFEDK',
      ];

      final decodedData = decodeAndVerifyUR(urParts);
      // 필요한 경우 decodedData를 사용하여 추가 검증 수행
    });

    test(
      '[keystone(bct-only) + sparrow (additionally P2TR)]: should decode crypto-account UR and extract values correctly',
      () {
        final urParts = [
          'UR:CRYPTO-ACCOUNT/7-3/LPATAXCFAOBBCYMOLRJELPHDPROEADCYETTIREVYAOLRTAADMWTAADDLOSAOWKAXHDCLAXPACFNDJELGWPKIPAVAIYNDLDAYCYHFFWJNFDKSWYPAJPTOWPBSOLHLEMRPIHGDGYAAHDCXEONYEYIMWNVEZMTLLYGUOETNLEVEADFEMEQZJNMSHFQDJOGLFHVWZOADYNLSFZFMAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSGHYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYFPLYFETLTAADMHTAADMWTAADDLOSAOWKAXHDCLAXBASOOELNRESRCHCLENLUPMTPTSRYGHSPMTFSSNUEGYBKJNGMAENEHF',
          'UR:CRYPTO-ACCOUNT/8-3/LPAYAXCFAOBBCYMOLRJELPHDPRPKKIKSZCYAYNSPVSGTUTHKQZHYINRODEHSJYTBFMRPETKBBSZENEAHPRTYJYFNBZQDMHAHMUSFHTJTLFCPRFYLFWSBECBAMSZMENRPIOGDHGUTHKBEMHNDQZJPRTBYZMCXLYOLNBRTPREEQZOXMORLIMGLHGLSTDGWRKVWBSLYAOLAFZENCTRPTDGERTTPADMETAATYNOLEYHGAOUEESHFYKKPSPHPBTWETSSTWLSWKECNESWFTSSKOSHKFHFWFWGSGTVTQZGMDYVWLECFADRSUTHKPFECHLMYVTOLFRVACTQZAESNTERELOBSSESGNNPEJNFSIODRFNIYKKHNCABTRFGDDMUYLOBDHHDASFDTZM',
          'UR:CRYPTO-ACCOUNT/9-3/LPASAXCFAOBBCYMOLRJELPHDPROEADCYETTIREVYAOLRTAADMWTAADDLOSAOWKAXHDCLAXPACFNDJELGWPKIPAVAIYNDLDAYCYHFFWJNFDKSWYPAJPTOWPBSOLHLEMRPIHGDGYAAHDCXEONYEYIMWNVEZMTLLYGUOETNLEVEADFEMEQZJNMSHFQDJOGLFHVWZOADYNLSFZFMAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSGHYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYFPLYFETLTAADMHTAADMWTAADDLOSAOWKAXHDCLAXBASOOELNRESRCHCLENLUPMTPTSRYGHSPMTFSSNUEGYBKJNWMZEYNHD',
          'UR:CRYPTO-ACCOUNT/10-3/LPBKAXCFAOBBCYMOLRJELPHDPRAYKEIDSKDEFXDTWDSOAAHDCXLTISMSMYIALATLIYMSFRTKCMIHWKLOHYPTSKTNJKDECFBTLDNYCSAXSGHTGMFGDYAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSEHYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYJLTEKGIDTAADMUTAADDLOSAOWKAXHDCLAOAEKPFSHPYAWSSNZMESJKNTCXFTWKBASSMSZOFMSWFWROSNBBRLGMETZMSBMKFYIMAAHDCXWPHHCWESOSBBFPCAFZAXMDWZRPLNSWIAGSDNJZKNCEGYOYMERNPLUTGASKDRJNVLAHTAADEHZEVTYTME',
          'UR:CRYPTO-ACCOUNT/11-3/LPBDAXCFAOBBCYMOLRJELPHDPROEADAEAOAEAMTAADDYOTADLNCSDWYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYONCHKSAOTAADNLTAADDLOSAOWKAXHDCLAXPKGUCPFWSOLRJSGHBEFTLDEONBOXCYBEFWLRAHHNQDIENYRKHPDSIEEHOEDTENWEAAHDCXCYLPRLEOYTBDWFCAPYOEFEMOTTZEVYAABEFZCFGRPDFEVANYJYLUBDSWBATDLGMYAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSHFYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYBNKPTIPLAEAEASCHVLMH',
        ];

        final decodedData = decodeAndVerifyUR(urParts);
        // 필요한 경우 decodedData를 사용하여 추가 검증 수행
      },
    );

    test('[jade]: should decode crypto-account UR and extract values correctly', () {
      final urParts = [
        'UR:CRYPTO-ACCOUNT/6-5/LPAMAHCSJKCYNLVTMTLUHGCFRKTNSOJNLRENASKTECJKECDKGYIYTTMYWEDYKILPCTLKHSTBTOUT',
        'UR:CRYPTO-ACCOUNT/1-5/LPADAHCSJKCYNLVTMTLUHGOEADCYLOCAFWTKAOLYTAADMWTAADDLOXAXHDCLAOVYTLDMFPEOSPRH',
        'UR:CRYPTO-ACCOUNT/2-5/LPAOAHCSJKCYNLVTMTLUHGCFRKTNSOJNLRENASKTECJKECDKGYIYTTMYWEDYKILPCTLKRDCELGBY',
        'UR:CRYPTO-ACCOUNT/3-5/LPAXAHCSJKCYNLVTMTLUHGAHWEFWSNQZRSAAHDCXJPWTMEMDDIZSZSVLSECNCAFRUTMEHYWMHDPR',
        'UR:CRYPTO-ACCOUNT/4-5/LPAAAHCSJKCYNLVTMTLUHGBYAYMNLPSWCNLFHESNWTFXBSMDEHJEVDGDKSAMTAADDYOTKGBTDTFZ',
        'UR:CRYPTO-ACCOUNT/5-5/LPAHAHCSJKCYNLVTMTLUHGADLNCSGHYKAEYKAEYKAOCYLOCAFWTKAXAXAYCYNDHLNEBGRYBKYLFE',
      ];

      final decodedData = decodeAndVerifyUR(urParts);
      // 필요한 경우 decodedData를 사용하여 추가 검증 수행
    });

    test('should failed with wrong ur types', () {
      final urParts = [
        'UR:CRYPTO-A/7-3/LPATAXCFAOBBCYMOLRJELPHDPROEADCYETTIREVYAOLRTAADMWTAADDLOSAOWKAXHDCLAXPACFNDJELGWPKIPAVAIYNDLDAYCYHFFWJNFDKSWYPAJPTOWPBSOLHLEMRPIHGDGYAAHDCXEONYEYIMWNVEZMTLLYGUOETNLEVEADFEMEQZJNMSHFQDJOGLFHVWZOADYNLSFZFMAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSGHYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYFPLYFETLTAADMHTAADMWTAADDLOSAOWKAXHDCLAXBASOOELNRESRCHCLENLUPMTPTSRYGHSPMTFSSNUEGYBKJNGMAENEHF',
        'UR:CRYPTO-B/8-3/LPAYAXCFAOBBCYMOLRJELPHDPRPKKIKSZCYAYNSPVSGTUTHKQZHYINRODEHSJYTBFMRPETKBBSZENEAHPRTYJYFNBZQDMHAHMUSFHTJTLFCPRFYLFWSBECBAMSZMENRPIOGDHGUTHKBEMHNDQZJPRTBYZMCXLYOLNBRTPREEQZOXMORLIMGLHGLSTDGWRKVWBSLYAOLAFZENCTRPTDGERTTPADMETAATYNOLEYHGAOUEESHFYKKPSPHPBTWETSSTWLSWKECNESWFTSSKOSHKFHFWFWGSGTVTQZGMDYVWLECFADRSUTHKPFECHLMYVTOLFRVACTQZAESNTERELOBSSESGNNPEJNFSIODRFNIYKKHNCABTRFGDDMUYLOBDHHDASFDTZM',
        'UR:CRYPTO-C/9-3/LPASAXCFAOBBCYMOLRJELPHDPROEADCYETTIREVYAOLRTAADMWTAADDLOSAOWKAXHDCLAXPACFNDJELGWPKIPAVAIYNDLDAYCYHFFWJNFDKSWYPAJPTOWPBSOLHLEMRPIHGDGYAAHDCXEONYEYIMWNVEZMTLLYGUOETNLEVEADFEMEQZJNMSHFQDJOGLFHVWZOADYNLSFZFMAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSGHYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYFPLYFETLTAADMHTAADMWTAADDLOSAOWKAXHDCLAXBASOOELNRESRCHCLENLUPMTPTSRYGHSPMTFSSNUEGYBKJNWMZEYNHD',
        'UR:CRYPTO-D/10-3/LPBKAXCFAOBBCYMOLRJELPHDPRAYKEIDSKDEFXDTWDSOAAHDCXLTISMSMYIALATLIYMSFRTKCMIHWKLOHYPTSKTNJKDECFBTLDNYCSAXSGHTGMFGDYAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSEHYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYJLTEKGIDTAADMUTAADDLOSAOWKAXHDCLAOAEKPFSHPYAWSSNZMESJKNTCXFTWKBASSMSZOFMSWFWROSNBBRLGMETZMSBMKFYIMAAHDCXWPHHCWESOSBBFPCAFZAXMDWZRPLNSWIAGSDNJZKNCEGYOYMERNPLUTGASKDRJNVLAHTAADEHZEVTYTME',
        'UR:CRYPTO-E/11-3/LPBDAXCFAOBBCYMOLRJELPHDPROEADAEAOAEAMTAADDYOTADLNCSDWYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYONCHKSAOTAADNLTAADDLOSAOWKAXHDCLAXPKGUCPFWSOLRJSGHBEFTLDEONBOXCYBEFWLRAHHNQDIENYRKHPDSIEEHOEDTENWEAAHDCXCYLPRLEOYTBDWFCAPYOEFEMOTTZEVYAABEFZCFGRPDFEVANYJYLUBDSWBATDLGMYAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSHFYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYBNKPTIPLAEAEASCHVLMH',
      ];

      decodeAndVerifyURFailed(urParts);
    });

    test('should failed with first wrong ur type', () {
      final urParts = [
        'UR:CRYPTO-A/7-3/LPATAXCFAOBBCYMOLRJELPHDPROEADCYETTIREVYAOLRTAADMWTAADDLOSAOWKAXHDCLAXPACFNDJELGWPKIPAVAIYNDLDAYCYHFFWJNFDKSWYPAJPTOWPBSOLHLEMRPIHGDGYAAHDCXEONYEYIMWNVEZMTLLYGUOETNLEVEADFEMEQZJNMSHFQDJOGLFHVWZOADYNLSFZFMAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSGHYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYFPLYFETLTAADMHTAADMWTAADDLOSAOWKAXHDCLAXBASOOELNRESRCHCLENLUPMTPTSRYGHSPMTFSSNUEGYBKJNGMAENEHF',
        'UR:CRYPTO-ACCOUNT/8-3/LPAYAXCFAOBBCYMOLRJELPHDPRPKKIKSZCYAYNSPVSGTUTHKQZHYINRODEHSJYTBFMRPETKBBSZENEAHPRTYJYFNBZQDMHAHMUSFHTJTLFCPRFYLFWSBECBAMSZMENRPIOGDHGUTHKBEMHNDQZJPRTBYZMCXLYOLNBRTPREEQZOXMORLIMGLHGLSTDGWRKVWBSLYAOLAFZENCTRPTDGERTTPADMETAATYNOLEYHGAOUEESHFYKKPSPHPBTWETSSTWLSWKECNESWFTSSKOSHKFHFWFWGSGTVTQZGMDYVWLECFADRSUTHKPFECHLMYVTOLFRVACTQZAESNTERELOBSSESGNNPEJNFSIODRFNIYKKHNCABTRFGDDMUYLOBDHHDASFDTZM',
        'UR:CRYPTO-ACCOUNT/9-3/LPASAXCFAOBBCYMOLRJELPHDPROEADCYETTIREVYAOLRTAADMWTAADDLOSAOWKAXHDCLAXPACFNDJELGWPKIPAVAIYNDLDAYCYHFFWJNFDKSWYPAJPTOWPBSOLHLEMRPIHGDGYAAHDCXEONYEYIMWNVEZMTLLYGUOETNLEVEADFEMEQZJNMSHFQDJOGLFHVWZOADYNLSFZFMAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSGHYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYFPLYFETLTAADMHTAADMWTAADDLOSAOWKAXHDCLAXBASOOELNRESRCHCLENLUPMTPTSRYGHSPMTFSSNUEGYBKJNWMZEYNHD',
        'UR:CRYPTO-ACCOUNT/10-3/LPBKAXCFAOBBCYMOLRJELPHDPRAYKEIDSKDEFXDTWDSOAAHDCXLTISMSMYIALATLIYMSFRTKCMIHWKLOHYPTSKTNJKDECFBTLDNYCSAXSGHTGMFGDYAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSEHYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYJLTEKGIDTAADMUTAADDLOSAOWKAXHDCLAOAEKPFSHPYAWSSNZMESJKNTCXFTWKBASSMSZOFMSWFWROSNBBRLGMETZMSBMKFYIMAAHDCXWPHHCWESOSBBFPCAFZAXMDWZRPLNSWIAGSDNJZKNCEGYOYMERNPLUTGASKDRJNVLAHTAADEHZEVTYTME',
        'UR:CRYPTO-ACCOUNT/11-3/LPBDAXCFAOBBCYMOLRJELPHDPROEADAEAOAEAMTAADDYOTADLNCSDWYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYONCHKSAOTAADNLTAADDLOSAOWKAXHDCLAXPKGUCPFWSOLRJSGHBEFTLDEONBOXCYBEFWLRAHHNQDIENYRKHPDSIEEHOEDTENWEAAHDCXCYLPRLEOYTBDWFCAPYOEFEMOTTZEVYAABEFZCFGRPDFEVANYJYLUBDSWBATDLGMYAHTAADEHOEADAEAOAEAMTAADDYOTADLNCSHFYKAEYKAEYKAOCYETTIREVYAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYBNKPTIPLAEAEASCHVLMH',
      ];

      decodeAndVerifyURFailed(urParts);
    });

    test('should failed with invalid UR type', () {
      String sourceJson = """
      [
  {
    "ExtPubKey": "vpub5YddfL4L4x1jZKmonL9sFqeZpxXs1YX43XRSxWHga5dCUisA5cDSumU4pYEXxh4djGXHXTXzz2J2UVEYHFJijkYXrYGZxP33b83qhccQ7rj",
    "MasterFingerprint": "CE4F9D06",
    "AccountKeyPath": "m/84'/1'/0'"
  },
  {
    "ExtPubKey": "upub5E3fKc9jb9Guvb658Tm9yWCVYjJf29Ejtusahu8gYMeWv6hUymhjX9aYW6KNUZHz5x7RCdo5qZy66A1QHqefKifkqbYx5xSCAVdYmUAGP6V",
    "MasterFingerprint": "CE4F9D06",
    "AccountKeyPath": "m/49'/1'/0'"
  },
  {
    "ExtPubKey": "tpubDDaz68yaoiBaJDZM1UJSQ1rGRjXFWB8L5VL8jMGyZdQMc6ipyRhzvDdyTusQMqAcvT6uvDaCko9VQJGscanTwnNGvBbyyNBbEEvXyJAC4Xy",
    "MasterFingerprint": "CE4F9D06",
    "AccountKeyPath": "m/44'/1'/0'"
  }
]
""";

      // 1. JSON String → UTF-8 bytes
      var jsonData = json.decode(sourceJson);

      // 2. CBOR 인코딩
      var cborEncoder = CBOREncoder();
      cborEncoder.encodeText(sourceJson);

      // 3. UR 포맷 생성
      var ur = UR("CRYPTO-ACCOUNT", cborEncoder.getBytes());

      // 4. UR 인코딩 준비
      var urEncoder = UREncoder(ur, 200); // 200 바이트 단위로 슬라이스 (원하면 조절 가능)

      // 5. String 배열 만들기
      List<String> parts = [];
      while (!urEncoder.isComplete) {
        parts.add(urEncoder.nextPart());
      }

      // 6. parts 출력
      for (var part in parts) {
        print(part);
      }
    });

    test('[keystone(btc only)]: should decode crypto-psbt UR and extract values correctly', () {
      final urParts = [
        'UR:CRYPTO-PSBT/265-3/LPCFADASAXCFADSPCYSELFGEKEHDMKYLUOLSKKGOVTIHCNAOAXREESAXBATTBWIDSSTAIHHSHTDYFXOSLRVDIDPMATCENLKTLBRTIMDSEHVALRVTJSWPHHPLHSSPPLFWFEINLTMDHFPFJPIMPEFLKIJLHEFZVWFZVYSKYLDYDTWZIAVLTBLDGUBWURCTSOSFNBNYCFHHJYTIIAJYWFESHYBGKGTBDNDTRYDNHSHESFBSTTRFPLSWCWFEAHYKLPHFRLADCPAMAXEEFTATKIVOTSIYSKUTJPKTHTDKAENTAHFEINASRKUYLOIEOYTEBARFCKKKVLETKBMYETEOCKDATO',
        'UR:CRYPTO-PSBT/266-3/LPCFADBKAXCFADSPCYSELFGEKEHDMKTIREVYGHAEAELAADAEAELAAEAEAELAAEAEAEAEAEAEAEAEAEADAXAAAEDPEHADADAACHCMAEBBJNMSCFREJLOXJZWMIAWLPLPKFHVLDNFYLSKIMNJSAECPAOAOLOCAZCFEKEBSASFPSFAAHLTKGOWFCKMNHKMDMKTOLAUTTLGRFLRDIECAFWTPHLLKCSETTIREVYGHAEAELAADAEAELAAEAEAELAADAEAEAEAEAEAEAEADAXAAJKQDSSAAADAACHCMAEBBFXFRLFOLBDLDLGSWBECHSOAHIEMNFWAYKBJNHNMSAEAXKEEHVD',
        'UR:CRYPTO-PSBT/267-3/LPCFADBDAXCFADSPCYSELFGEKEHDMKHKADSKJOJKIDJYZMADAEJSAOAEAEAEADTSCFYNSRKEBAFZGHLBRPYKRFSBESCFWMHFBDWSZCRSVDDRCMKPKIFGGYZTDIWDIOAEAEAEAEAEZMZMZMZMAOAEDPEHADAEAEAEAECMAEBBJNMSCFREJLOXJZWMIAWLPLPKFHVLDNFYLSKIMNJSJKQDSSAAAEAEAEAECMAEBBFXFRLFOLBDLDLGSWBECHSOAHIEMNFWAYKBJNHNMSAEAEAEAEAEADADCTAEVYYKAHAEAEAEAECMAEBBKESWFXTIOTPTZSBTRYRELUTSLNLAPYGSLN',
        'UR:CRYPTO-PSBT/267-3/LPCFADBDAXCFADSPCYSELFGEKEHDMKHKADSKJOJKIDJYZMADAEJSAOAEAEAEADTSCFYNSRKEBAFZGHLBRPYKRFSBESCFWMHFBDWSZCRSVDDRCMKPKIFGGYZTDIWDIOAEAEAEAEAEZMZMZMZMAOAEDPEHADAEAEAEAECMAEBBJNMSCFREJLOXJZWMIAWLPLPKFHVLDNFYLSKIMNJSJKQDSSAAAEAEAEAECMAEBBFXFRLFOLBDLDLGSWBECHSOAHIEMNFWAYKBJNHNMSAEAEAEAEAEADADCTAEVYYKAHAEAEAEAECMAEBBKESWFXTIOTPTZSBTRYRELUTSLNLAPYGSLN',
        'UR:CRYPTO-PSBT/268-3/LPCFADBNAXCFADSPCYSELFGEKEHDMKDIINIDDPGOVTVWCPAOAXECESAXBAGYBWIDSSTAIHHSHTDYFXOLLTVLIDLAENCAMKJKISTBIMEYHHJSNTGOCKFDDYFEAOCLAEVSKNLEPSTTTLSNZTCWPEIHLBJNTSHLCSAHNTSGZEJSVWYNFMDWLSKNGTNTLNLEGYAOCXFLSFCHEOIMATINPAVYAXNNIAWYZONSHHLBHSHEGSBATTRFDMSWCWFELPWKLPHFRLADCPAMAXECESAXBAGYBWIDSSTAIHHSHTDYFXOLLTVLIDLAENCAMKJKISTBIMEYHHJSNTGOCKCSETHHEMCEDW',
        'UR:CRYPTO-PSBT/268-3/LPCFADBNAXCFADSPCYSELFGEKEHDMKDIINIDDPGOVTVWCPAOAXECESAXBAGYBWIDSSTAIHHSHTDYFXOLLTVLIDLAENCAMKJKISTBIMEYHHJSNTGOCKFDDYFEAOCLAEVSKNLEPSTTTLSNZTCWPEIHLBJNTSHLCSAHNTSGZEJSVWYNFMDWLSKNGTNTLNLEGYAOCXFLSFCHEOIMATINPAVYAXNNIAWYZONSHHLBHSHEGSBATTRFDMSWCWFELPWKLPHFRLADCPAMAXECESAXBAGYBWIDSSTAIHHSHTDYFXOLLTVLIDLAENCAMKJKISTBIMEYHHJSNTGOCKCSETHHEMCEDW',
        'UR:CRYPTO-PSBT/268-3/LPCFADBNAXCFADSPCYSELFGEKEHDMKDIINIDDPGOVTVWCPAOAXECESAXBAGYBWIDSSTAIHHSHTDYFXOLLTVLIDLAENCAMKJKISTBIMEYHHJSNTGOCKFDDYFEAOCLAEVSKNLEPSTTTLSNZTCWPEIHLBJNTSHLCSAHNTSGZEJSVWYNFMDWLSKNGTNTLNLEGYAOCXFLSFCHEOIMATINPAVYAXNNIAWYZONSHHLBHSHEGSBATTRFDMSWCWFELPWKLPHFRLADCPAMAXECESAXBAGYBWIDSSTAIHHSHTDYFXOLLTVLIDLAENCAMKJKISTBIMEYHHJSNTGOCKCSETHHEMCEDW',
        'UR:CRYPTO-PSBT/269-3/LPCFADBTAXCFADSPCYSELFGEKEHDMKPLUTFGASDSLFBYUOAXAXSSFRAXBATTBGREUTDLOLCAGHJOCHTPEYBGUEIYFMAHJPCLJYDLMSNLTBSFMOMDBNPKBTGMFGCPSOFWFEINLTMDPTGWLGMDPMFLGDHYHYFZVWFZVYTEYLDKFYIHKNHFRHDPFHYARFYNIOIYNEKKEYCSYLPMWEAHLALENYCMKGTBDNDTPYDNKPCEYLLGKTRLDIGRUTGOBGFNLAEYESFXDRKSJTGHPMATKIVOTSIYSSUOJNKTRKTTAHNTAHFEINCTRKTKWKOEVOAXPMBZVEJYHYLGYKHDRNURVTHSGT',
        'UR:CRYPTO-PSBT/269-3/LPCFADBTAXCFADSPCYSELFGEKEHDMKPLUTFGASDSLFBYUOAXAXSSFRAXBATTBGREUTDLOLCAGHJOCHTPEYBGUEIYFMAHJPCLJYDLMSNLTBSFMOMDBNPKBTGMFGCPSOFWFEINLTMDPTGWLGMDPMFLGDHYHYFZVWFZVYTEYLDKFYIHKNHFRHDPFHYARFYNIOIYNEKKEYCSYLPMWEAHLALENYCMKGTBDNDTPYDNKPCEYLLGKTRLDIGRUTGOBGFNLAEYESFXDRKSJTGHPMATKIVOTSIYSSUOJNKTRKTTAHNTAHFEINCTRKTKWKOEVOAXPMBZVEJYHYLGYKHDRNURVTHSGT',
        'UR:CRYPTO-PSBT/269-3/LPCFADBTAXCFADSPCYSELFGEKEHDMKPLUTFGASDSLFBYUOAXAXSSFRAXBATTBGREUTDLOLCAGHJOCHTPEYBGUEIYFMAHJPCLJYDLMSNLTBSFMOMDBNPKBTGMFGCPSOFWFEINLTMDPTGWLGMDPMFLGDHYHYFZVWFZVYTEYLDKFYIHKNHFRHDPFHYARFYNIOIYNEKKEYCSYLPMWEAHLALENYCMKGTBDNDTPYDNKPCEYLLGKTRLDIGRUTGOBGFNLAEYESFXDRKSJTGHPMATKIVOTSIYSSUOJNKTRKTTAHNTAHFEINCTRKTKWKOEVOAXPMBZVEJYHYLGYKHDRNURVTHSGT',
        'UR:CRYPTO-PSBT/270-3/LPCFADBAAXCFADSPCYSELFGEKEHDMKDIINIDDPGOVTVWCPAOAXECESAXBAGYBWIDSSTAIHHSHTDYFXOLLTVLIDLAENCAMKJKISTBIMEYHHJSNTGOCKFDDYFEAOCLAEVSKNLEPSTTTLSNZTCWPEIHLBJNTSHLCSAHNTSGZEJSVWYNFMDWLSKNGTNTLNLEGYAOCXFLSFCHEOIMATINPAVYAXNNIAWYZONSHHLBHSHEGSBATTRFDMSWCWFELPWKLPHFRLADCPAMAXECESAXBAGYBWIDSSTAIHHSHTDYFXOLLTVLIDLAENCAMKJKISTBIMEYHHJSNTGOCKCSETJLCAUTNY',
        'UR:CRYPTO-PSBT/270-3/LPCFADBAAXCFADSPCYSELFGEKEHDMKDIINIDDPGOVTVWCPAOAXECESAXBAGYBWIDSSTAIHHSHTDYFXOLLTVLIDLAENCAMKJKISTBIMEYHHJSNTGOCKFDDYFEAOCLAEVSKNLEPSTTTLSNZTCWPEIHLBJNTSHLCSAHNTSGZEJSVWYNFMDWLSKNGTNTLNLEGYAOCXFLSFCHEOIMATINPAVYAXNNIAWYZONSHHLBHSHEGSBATTRFDMSWCWFELPWKLPHFRLADCPAMAXECESAXBAGYBWIDSSTAIHHSHTDYFXOLLTVLIDLAENCAMKJKISTBIMEYHHJSNTGOCKCSETJLCAUTNY',
        'UR:CRYPTO-PSBT/270-3/LPCFADBAAXCFADSPCYSELFGEKEHDMKDIINIDDPGOVTVWCPAOAXECESAXBAGYBWIDSSTAIHHSHTDYFXOLLTVLIDLAENCAMKJKISTBIMEYHHJSNTGOCKFDDYFEAOCLAEVSKNLEPSTTTLSNZTCWPEIHLBJNTSHLCSAHNTSGZEJSVWYNFMDWLSKNGTNTLNLEGYAOCXFLSFCHEOIMATINPAVYAXNNIAWYZONSHHLBHSHEGSBATTRFDMSWCWFELPWKLPHFRLADCPAMAXECESAXBAGYBWIDSSTAIHHSHTDYFXOLLTVLIDLAENCAMKJKISTBIMEYHHJSNTGOCKCSETJLCAUTNY',
        'UR:CRYPTO-PSBT/271-3/LPCFADBSAXCFADSPCYSELFGEKEHDMKHKADSKJOJKIDJYZMADAEJSAOAEAEAEADTSCFYNSRKEBAFZGHLBRPYKRFSBESCFWMHFBDWSZCRSVDDRCMKPKIFGGYZTDIWDIOAEAEAEAEAEZMZMZMZMAOAEDPEHADAEAEAEAECMAEBBJNMSCFREJLOXJZWMIAWLPLPKFHVLDNFYLSKIMNJSJKQDSSAAAEAEAEAECMAEBBFXFRLFOLBDLDLGSWBECHSOAHIEMNFWAYKBJNHNMSAEAEAEAEAEADADCTAEVYYKAHAEAEAEAECMAEBBKESWFXTIOTPTZSBTRYRELUTSLNVAZETKWD',
        'UR:CRYPTO-PSBT/271-3/LPCFADBSAXCFADSPCYSELFGEKEHDMKHKADSKJOJKIDJYZMADAEJSAOAEAEAEADTSCFYNSRKEBAFZGHLBRPYKRFSBESCFWMHFBDWSZCRSVDDRCMKPKIFGGYZTDIWDIOAEAEAEAEAEZMZMZMZMAOAEDPEHADAEAEAEAECMAEBBJNMSCFREJLOXJZWMIAWLPLPKFHVLDNFYLSKIMNJSJKQDSSAAAEAEAEAECMAEBBFXFRLFOLBDLDLGSWBECHSOAHIEMNFWAYKBJNHNMSAEAEAEAEAEADADCTAEVYYKAHAEAEAEAECMAEBBKESWFXTIOTPTZSBTRYRELUTSLNVAZETKWD',
        'UR:CRYPTO-PSBT/271-3/LPCFADBSAXCFADSPCYSELFGEKEHDMKHKADSKJOJKIDJYZMADAEJSAOAEAEAEADTSCFYNSRKEBAFZGHLBRPYKRFSBESCFWMHFBDWSZCRSVDDRCMKPKIFGGYZTDIWDIOAEAEAEAEAEZMZMZMZMAOAEDPEHADAEAEAEAECMAEBBJNMSCFREJLOXJZWMIAWLPLPKFHVLDNFYLSKIMNJSJKQDSSAAAEAEAEAECMAEBBFXFRLFOLBDLDLGSWBECHSOAHIEMNFWAYKBJNHNMSAEAEAEAEAEADADCTAEVYYKAHAEAEAEAECMAEBBKESWFXTIOTPTZSBTRYRELUTSLNVAZETKWD',
        'UR:CRYPTO-PSBT/272-3/LPCFADBEAXCFADSPCYSELFGEKEHDMKPLUTFGASDSLFBYUOAXAXSSFRAXBATTBGREUTDLOLCAGHJOCHTPEYBGUEIYFMAHJPCLJYDLMSNLTBSFMOMDBNPKBTGMFGCPSOFWFEINLTMDPTGWLGMDPMFLGDHYHYFZVWFZVYTEYLDKFYIHKNHFRHDPFHYARFYNIOIYNEKKEYCSYLPMWEAHLALENYCMKGTBDNDTPYDNKPCEYLLGKTRLDIGRUTGOBGFNLAEYESFXDRKSJTGHPMATKIVOTSIYSSUOJNKTRKTTAHNTAHFEINCTRKTKWKOEVOAXPMBZVEJYHYLGYKHDRNDMPSMYTE',
        'UR:CRYPTO-PSBT/272-3/LPCFADBEAXCFADSPCYSELFGEKEHDMKPLUTFGASDSLFBYUOAXAXSSFRAXBATTBGREUTDLOLCAGHJOCHTPEYBGUEIYFMAHJPCLJYDLMSNLTBSFMOMDBNPKBTGMFGCPSOFWFEINLTMDPTGWLGMDPMFLGDHYHYFZVWFZVYTEYLDKFYIHKNHFRHDPFHYARFYNIOIYNEKKEYCSYLPMWEAHLALENYCMKGTBDNDTPYDNKPCEYLLGKTRLDIGRUTGOBGFNLAEYESFXDRKSJTGHPMATKIVOTSIYSSUOJNKTRKTTAHNTAHFEINCTRKTKWKOEVOAXPMBZVEJYHYLGYKHDRNDMPSMYTE',
        'UR:CRYPTO-PSBT/272-3/LPCFADBEAXCFADSPCYSELFGEKEHDMKPLUTFGASDSLFBYUOAXAXSSFRAXBATTBGREUTDLOLCAGHJOCHTPEYBGUEIYFMAHJPCLJYDLMSNLTBSFMOMDBNPKBTGMFGCPSOFWFEINLTMDPTGWLGMDPMFLGDHYHYFZVWFZVYTEYLDKFYIHKNHFRHDPFHYARFYNIOIYNEKKEYCSYLPMWEAHLALENYCMKGTBDNDTPYDNKPCEYLLGKTRLDIGRUTGOBGFNLAEYESFXDRKSJTGHPMATKIVOTSIYSSUOJNKTRKTTAHNTAHFEINCTRKTKWKOEVOAXPMBZVEJYHYLGYKHDRNDMPSMYTE',
      ];

      final decoder = URDecoder();

      // UR 조각들을 디코딩
      int index = 0;
      for (final part in urParts) {
        Logger.log('Part $index: ${decoder.receivePart(part)}');
        Logger.log('isCompleted $index: ${decoder.isComplete()}');
        Logger.log('expectedType: ${decoder.expectedType}');
        index++;
      }

      expect(decoder.isComplete(), true, reason: 'UR decoding should be complete');
      final ur = decoder.result;
      final cborBytes = ur.cbor;
      final decodedCbor = cbor.decode(cborBytes);
      expect(decodedCbor, isA<CborBytes>(), reason: 'Decoded CBOR should be a CborBytes');
    });
  });
}

Map<String, dynamic> decodeAndVerifyUR(List<String> urParts) {
  final decoder = URDecoder();

  // UR 조각들을 디코딩
  int index = 0;
  for (final part in urParts) {
    Logger.log('Part $index: ${decoder.receivePart(part)}');
    Logger.log('isCompleted $index: ${decoder.isComplete()}');
    Logger.log('expectedType: ${decoder.expectedType}');
    index++;
  }

  expect(decoder.isComplete(), true, reason: 'UR decoding should be complete');

  final ur = decoder.result;
  final cborBytes = ur.cbor;

  // CBOR 바이트 배열을 디코딩하여 Dart 객체로 변환
  final decodedCbor = cbor.decode(cborBytes);
  expect(decodedCbor, isA<Map>(), reason: 'Decoded CBOR should be a Map');

  Map<dynamic, dynamic> cborMap = decodedCbor as Map<dynamic, dynamic>;
  printMapRecursive(cborMap);
  Map<String, dynamic> jsonCompatibleMap = convertKeysToString(cborMap);

  // MFP 값 검증
  var mfpValue = jsonCompatibleMap["1"].toInt().toRadixString(16).toUpperCase();
  expect(mfpValue, isA<String>(), reason: 'MFP value should be a hex string');

  // 공개키와 체인코드 검증
  var accountData = jsonCompatibleMap["2"][0];
  expect(accountData["3"], isNotNull, reason: 'Public key should exist');
  expect(accountData["4"], isNotNull, reason: 'Chain code should exist');

  return jsonCompatibleMap;
}

void printMapRecursive(Map<dynamic, dynamic> map, {int indent = 0}) {
  final spaces = ' ' * indent;
  map.forEach((key, value) {
    if (value is Map) {
      print('$spaces$key:');
      printMapRecursive(value, indent: indent + 2);
    } else {
      print('$spaces$key: $value');
    }
  });
}

void decodeAndVerifyURFailed(List<String> urParts) {
  final decoder = URDecoder();

  // UR 조각들을 디코딩
  int index = 0;
  for (final part in urParts) {
    Logger.log('Part $index: ${decoder.receivePart(part)}');
    Logger.log('isCompleted $index: ${decoder.isComplete()}');
    Logger.log('expectedType: ${decoder.expectedType}');

    index++;
  }

  expect(decoder.isComplete(), false, reason: 'UR decoding should be failed');

  final ur = decoder.result;
  expect(ur, isNull, reason: 'UR should be null');
}
