// Code generated by gobind. DO NOT EDIT.

// Java class bridge.Bridge is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java coconut_wallet/go
package bridge;

import go.Seq;

public abstract class Bridge {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Bridge() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	private static final class proxyTransport implements Seq.Proxy, Transport {
		private final int refnum;
		
		@Override public final int incRefnum() {
		      Seq.incGoRef(refnum, this);
		      return refnum;
		}
		
		proxyTransport(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
		
		public native void close() throws Exception;
		public native byte[] read(long n) throws Exception;
		public native long write(byte[] p0) throws Exception;
	}
	
	
	/**
	 * BTCAddress returns a Bitcoin address for the given keypath and script type.
	 */
	public static native String btcAddress(String deviceID, long coin, String keypath, String scriptType, boolean display) throws Exception;
	/**
	 * BTCSignMessage signs a message.
	 */
	public static native String btcSignMessage(String deviceID, long coin, String keypath, String scriptType, byte[] message) throws Exception;
	/**
	 * BTCSignPSBT signs a PSBT. Returns the signed PSBT bytes.
	 */
	public static native byte[] btcSignPSBT(String deviceID, long coin, byte[] psbtBytes, long formatUnit) throws Exception;
	/**
	 * BTCXPub returns the extended public key at the given derivation path.
	 */
	public static native String btcxPub(String deviceID, long coin, String keypath, long xpubType, boolean display) throws Exception;
	/**
	 * ChannelHashVerify confirms the pairing channel hash from the host side.
	Must be called after Init() before any other device operations.
	 */
	public static native void channelHashVerify(String deviceID, boolean ok) throws Exception;
	/**
	 * ClearPrevTxHexes clears stored prevtx hexes for a device.
	 */
	public static native void clearPrevTxHexes(String deviceID);
	/**
	 * Connect opens a connection to a BitBox02 device.
	Uses nil version/product — device info is queried via OP_INFO.
	 */
	public static native String connect(Transport transport) throws Exception;
	/**
	 * ConnectWithInfo opens a connection with explicit product and version info.
	Use this for simulators or transports that don&#39;t provide USB HID descriptors.
	product: &#34;btc-only&#34; or &#34;multi&#34;
	version: e.g. &#34;9.26.1&#34;
	 */
	public static native String connectWithInfo(Transport transport, String product, String version) throws Exception;
	/**
	 * DeviceInitialized returns true if the device has a seed loaded.
	 */
	public static native boolean deviceInitialized(String deviceID) throws Exception;
	/**
	 * Disconnect closes the connection to a device.
	 */
	public static native void disconnect(String deviceID) throws Exception;
	/**
	 * Init performs the Noise handshake and pairing.
	 */
	public static native String init(String deviceID) throws Exception;
	/**
	 * ListDevices returns device IDs of currently connected devices.
	 */
	public static native String listDevices() throws Exception;
	/**
	 * LoadConfig loads a previously saved noise config from JSON.
	 */
	public static native void loadConfig(String deviceID, String configJSON) throws Exception;
	/**
	 * RestoreFromMnemonic restores the device from the built-in simulator mnemonic.
	 */
	public static native void restoreFromMnemonic(String deviceID) throws Exception;
	/**
	 * RootFingerprint returns the keystore&#39;s root fingerprint as a hex string.
	 */
	public static native String rootFingerprint(String deviceID) throws Exception;
	/**
	 * SaveConfig serializes the device&#39;s noise config to JSON.
	 */
	public static native String saveConfig(String deviceID) throws Exception;
	/**
	 * SetLoggerEnabled toggles logging.
	 */
	public static native void setLoggerEnabled(boolean v);
	/**
	 * SetPassword creates a new random wallet with the given seed length (16 or 32 bytes).
	 */
	public static native void setPassword(String deviceID, long seedLen) throws Exception;
	/**
	 * SetPrevTxHex stores a previous transaction raw hex for a given device and input index.
	These will be injected as NonWitnessUtxo into the PSBT before signing.
	 */
	public static native void setPrevTxHex(String deviceID, long inputIndex, String rawTxHex);
}
