// Code generated by gobind. DO NOT EDIT.

// Java class bridge.Transport is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java coconut_wallet/go
package bridge;

import go.Seq;

/**
 * Transport is the interface that gomobile binds to native platforms.
Uses the bitbox-wallet-app pattern: Read returns a new byte slice instead of
filling a provided buffer (gomobile does not copy back modified []byte params).
 */
public interface Transport {
	public void close() throws Exception;
	public byte[] read(long n) throws Exception;
	public long write(byte[] p0) throws Exception;
	
}

